<?php
/**
 * @file
 * Contains invite_by_email.module.
 */

/**
 * Implements hook_form_alter().
 */
function invite_by_email_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'invite_type_add_form' || $form_id == 'invite_type_edit_form') {
    $invite_type = $form_state->getFormObject()->getEntity();
    $data = unserialize($invite_type->getData());

    $invite_by_email_settings = !empty($data) ? $data : array(
      'use_default' => TRUE,
      'subject_editable' => '',
      'mail_subject' => '',
      'mail_template' => '',
    );

    $form['invite_by_email'] = array(
      '#type' => 'fieldset',
      '#title' => t('Invite by e-mail message settings'),
      '#tree' => TRUE,
      '#attributes' => array(
        'class' => array(
          'invite-by-email-wrapper',
        ),
      ),
      '#states' => array(
        'invisible' => array(
          ':input[name="send_method[invite_by_email]"]' => array('checked' => FALSE),
        )
      ),
    );

    $form['invite_by_email']['use_default'] = array(
      '#type' => 'checkbox',
      '#title' => t('Use default settings'),
//    '#description' => t('Use !default_link mail template and settings', array('!default_link' => Link::fromTextAndUrl(t('default'), 'admin/config/people/invite/by_mail'))),
      '#default_value' => $invite_by_email_settings['use_default'],
      '#states' => array(
        'invisible' => array(
          ':input[name="invite_by_email"]' => array('!value' => 'invite_by_email'),
        ),
      ),
    );

    $form['invite_by_email']['subject_editable'] = array(
      '#type' => 'checkbox',
      '#title' => t('Editable subject'),
      '#description' => t('Choose whether users should be able to customize the subject.'),
      '#default_value' => $invite_by_email_settings['subject_editable'],
      '#states' => array(
        'invisible' => array(
          ':input[name="invite_by_email[use_default]"]' => array('checked' => TRUE),
        ),
      ),
    );

    $form['invite_by_email']['help'] = array(
      '#type' => 'container',
      'help' => array(
        '#markup' => t('You may update the default values for Subject and Body for this content type on the fields edit page.'),
      ),
      '#states' => array(
        'invisible' => array(
          ':input[name="invite_by_email[use_default]"]' => array('checked' => TRUE),
        ),
      ),
    );

    // Put our submit in top of list to ensure, that values will be added to 'data'
    array_unshift($form['actions']['submit']['#submit'], 'invite_by_email_form_invite_type_form_submit');
  }
}

/**
 * Submit handler for invite types form.
 *
 * @param $form
 * @param $form_state
 */
function invite_by_email_form_invite_type_form_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $form_state->setValue('data', serialize($form_state->getValue('invite_by_email')));
}